const roomTypeNames = [{name: "Select one"},
{ name: "Apartment" },
{ name: "Condominium" },
{ name: "Guesthouse" },
{ name: "House" },
{ name: "Hotel" },
{ name: "n-law" },
{ name: "Guest suite" },
{ name: "Townhosue" },
{ name: "Vacation home" },
{ name: "───────────────────" },
{ name: "Boat" },
{ name: "Bungalow" },
{ name: "Cabin" },
{ name: "Castle" },
{ name: "Cave" },
{ name: "Chalet" },
{ name: "Dorm" },
{ name: "Earth House" },
{ name: "Igloo" },
{ name: "Island" },
{ name: "Lighthouse" },
{ name: "Plane" },
{ name: "Camper" },
{ name: "Tent" },
{ name: "Tipi" },
{ name: "Train" },
{ name: "Treehouse" },
{ name: "Villa" },
{ name: "Yurt" }];
